spring:
  application:
    name: api-gateway
server:
  port: 8800

zuul:
  routes:
    myDataService:
      path: /thatbank/**
      url: http://localhost:8088/v1/
      strip-prefix: true
ribbon:
  eureka:
    enabled: false